<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Anjal.Smtp\Anjal.Smtp.csproj" />
    <ProjectReference Include="..\Anjal.Api\Anjal.Api.csproj" />
    <ProjectReference Include="..\Anjal.Store\Anjal.Store.csproj" />
    <ProjectReference Include="..\Anjal.Routing\Anjal.Routing.csproj" />
    <ProjectReference Include="..\Anjal.Mime\Anjal.Mime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
