using System.Globalization;
using System.Reflection;
using System.Text.Json;

namespace Anjal.Webmail.Services;

/// <summary>
/// Every word the webmail shows, in the languages the owner has switched on
/// (rc.11, D-92). The word lists are generated by tools/gen_words.py from the
/// owner's six-language sheet and built into the program. A word missing from
/// a language shows in English - never as a blank or a code.
/// </summary>
public sealed class Words
{
    private static readonly Dictionary<string, string> NativeNames = new(StringComparer.Ordinal)
    {
        ["en"] = "English",
        ["ta"] = "\u0BA4\u0BAE\u0BBF\u0BB4\u0BCD",
        ["ml"] = "\u0D2E\u0D32\u0D2F\u0D3E\u0D33\u0D02",
        ["hi"] = "\u0939\u093F\u0928\u094D\u0926\u0940",
        ["mr"] = "\u092E\u0930\u093E\u0920\u0940",
        ["gu"] = "\u0A97\u0AC1\u0A9C\u0AB0\u0ABE\u0AA4\u0AC0",
    };

    private readonly Dictionary<string, Lexicon> lexicons;
    private readonly Dictionary<string, Lexicon> previews = new(StringComparer.Ordinal);

    /// <summary>Build from word lists already read; English is always present.</summary>
    /// <param name="lists">Language code to (English word to that language's word).</param>
    /// <param name="previewLists">
    /// Languages not yet switched on, as drafted (rc.15, item 41): only the service's operators
    /// may choose them, to look at a language before its words are checked.
    /// </param>
    public Words(IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> lists, IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>? previewLists = null)
    {
        ArgumentNullException.ThrowIfNull(lists);
        foreach (KeyValuePair<string, IReadOnlyDictionary<string, string>> list in previewLists ?? new Dictionary<string, IReadOnlyDictionary<string, string>>())
        {
            if (!lists.ContainsKey(list.Key) && !string.Equals(list.Key, "en", StringComparison.Ordinal))
            {
                this.previews[list.Key] = new Lexicon(list.Key, list.Value, preview: true);
            }
        }
        this.lexicons = new Dictionary<string, Lexicon>(StringComparer.Ordinal)
        {
            ["en"] = new Lexicon("en", new Dictionary<string, string>(StringComparer.Ordinal)),
        };
        foreach (KeyValuePair<string, IReadOnlyDictionary<string, string>> list in lists)
        {
            if (!string.Equals(list.Key, "en", StringComparison.Ordinal))
            {
                this.lexicons[list.Key] = new Lexicon(list.Key, list.Value);
            }
        }
    }

    /// <summary>The words built into the program, once loaded (for the dates' day and month names, rc.15).</summary>
    public static Words? Current { get; private set; }

    /// <summary>The languages switched on, English first.</summary>
    public IReadOnlyList<string> Enabled => this.lexicons.Keys.OrderBy(k => k == "en" ? 0 : 1).ThenBy(k => k, StringComparer.Ordinal).ToList();

    /// <summary>Read the word lists built into the program.</summary>
    /// <returns>The words.</returns>
    public static Words Load()
    {
        Assembly assembly = typeof(Words).Assembly;
        var lists = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal);
        var previewLists = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal);
        foreach (string name in assembly.GetManifestResourceNames())
        {
            if (!name.Contains(".Resources.Words.", StringComparison.Ordinal) || !name.EndsWith(".json", StringComparison.Ordinal))
            {
                continue;
            }
            using Stream stream = assembly.GetManifestResourceStream(name) ?? throw new InvalidOperationException("Missing word list " + name);
            using JsonDocument doc = JsonDocument.Parse(stream);
            string code = doc.RootElement.GetProperty("language").GetString() ?? string.Empty;
            var words = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (JsonProperty p in doc.RootElement.GetProperty("words").EnumerateObject())
            {
                words[p.Name] = p.Value.GetString() ?? p.Name;
            }
            bool preview = doc.RootElement.TryGetProperty("preview", out JsonElement p2) && p2.ValueKind == JsonValueKind.True;
            if (string.Equals(code, "en", StringComparison.Ordinal))
            {
                Lexicon.Listed = new HashSet<string>(words.Keys, StringComparer.Ordinal);
            }
            (preview ? previewLists : lists)[code] = words;
        }
        Words loaded = new(lists, previewLists);
        Current = loaded;
        return loaded;
    }

    /// <summary>
    /// The letter the mark carries for a language (SPEC-11 item 39, "every
    /// script"): the first letter of the reader's language.
    /// </summary>
    /// <param name="code">A language code.</param>
    /// <returns>A, அ, അ, अ or અ; A when unknown.</returns>
    public static string MarkLetter(string? code) => code switch
    {
        "ta" => "\u0B85",
        "ml" => "\u0D05",
        "hi" or "mr" => "\u0905",
        "gu" => "\u0A85",
        _ => "A",
    };

    /// <summary>
    /// The script of a language's mark letter, naming the logo files drawn for it
    /// (DES-11 D6): latn, taml, mlym, deva or gujr.
    /// </summary>
    /// <param name="code">A language code.</param>
    /// <returns>The script's four-letter name; latn when unknown.</returns>
    public static string MarkScript(string? code) => code switch
    {
        "ta" => "taml",
        "ml" => "mlym",
        "hi" or "mr" => "deva",
        "gu" => "gujr",
        _ => "latn",
    };

    /// <summary>A language's own name, written in its own script, such as \u0BA4\u0BAE\u0BBF\u0BB4\u0BCD for Tamil.</summary>
    /// <param name="code">A language code.</param>
    /// <returns>The name, or the code when unknown.</returns>
    public static string NativeName(string code)
    {
        ArgumentNullException.ThrowIfNull(code);
        return NativeNames.TryGetValue(code, out string? name) ? name : code;
    }

    /// <summary>True when this language may be looked at by the service's operators before it is switched on (rc.15, item 41).</summary>
    /// <param name="code">A language code.</param>
    /// <returns>True for a language in preview.</returns>
    public bool IsPreview(string? code) => code is not null && this.previews.ContainsKey(code);

    /// <summary>True when people may choose this language.</summary>
    /// <param name="code">A language code.</param>
    /// <returns>Whether it is switched on.</returns>
    public bool IsEnabled(string? code) => code is not null && this.lexicons.ContainsKey(code);

    /// <summary>The words in a language; English when it is not switched on.</summary>
    /// <param name="code">A language code, or null.</param>
    /// <returns>The lexicon.</returns>
    public Lexicon For(string? code) =>
        code is not null && (this.lexicons.TryGetValue(code, out Lexicon? lexicon) || this.previews.TryGetValue(code, out lexicon)) ? lexicon : this.lexicons["en"];
}

/// <summary>The words of one language.</summary>
public sealed class Lexicon
{
    private static readonly string[] Months = CultureInfo.InvariantCulture.DateTimeFormat.MonthNames.Where(m => m.Length > 0).ToArray();

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<string, bool> Missed = new(StringComparer.Ordinal);

    private readonly IReadOnlyDictionary<string, string> words;

    /// <summary>
    /// Every English word in the owner's word list (rc.15, item 41), once the lists are loaded.
    /// A screen asking for anything else is noted in <see cref="Unlisted"/>: it would show in
    /// English in every language, so the tests fail on it.
    /// </summary>
    public static IReadOnlySet<string>? Listed { get; set; }

    /// <summary>What screens have asked for that is not in the word list (at most 1,000 kept).</summary>
    public static IReadOnlyCollection<string> Unlisted => Missed.Keys.ToList();

    /// <summary>Forget what was noted in <see cref="Unlisted"/> (tests).</summary>
    public static void ClearUnlisted() => Missed.Clear();

    /// <summary>Wrap one language's words.</summary>
    /// <param name="language">The language code.</param>
    /// <param name="words">English word to this language's word.</param>
    /// <param name="preview">True for a language not yet switched on, shown only to operators (rc.15, item 41).</param>
    public Lexicon(string language, IReadOnlyDictionary<string, string> words, bool preview = false)
    {
        this.IsPreview = preview;
        ArgumentNullException.ThrowIfNull(language);
        ArgumentNullException.ThrowIfNull(words);
        this.Language = language;
        this.words = words;
    }

    /// <summary>True when these are drafts not yet checked, shown only to the service's operators.</summary>
    public bool IsPreview { get; }

    /// <summary>The language code, such as en or ta; also the page's lang attribute.</summary>
    public string Language { get; }

    /// <summary>
    /// A folder's name to show: the standard folders in this language (INBOX
    /// shows as Inbox), the person's own folders exactly as they named them.
    /// The one rule every screen uses, so no two can differ.
    /// </summary>
    /// <param name="folder">The folder's stored name.</param>
    /// <returns>The name to show.</returns>
    public string Folder(string folder)
    {
        ArgumentNullException.ThrowIfNull(folder);
        return folder switch
        {
            "INBOX" => this["Inbox"],
            "Sent" or "Drafts" or "Junk" or "Trash" or "Archive" or "Scheduled" or "Outbox" => this[folder],
            _ => folder,
        };
    }

    /// <summary>
    /// A heading of the list's day groups in this language: Today, Yesterday,
    /// Earlier this week, Earlier this month, or a month and year such as
    /// "September 2026", whose month is a word and whose year is not.
    /// </summary>
    /// <param name="heading">The heading in English.</param>
    /// <returns>The heading to show.</returns>
    public string Heading(string heading)
    {
        ArgumentNullException.ThrowIfNull(heading);
        int space = heading.LastIndexOf(' ');
        return space > 0 && Months.Contains(heading[..space], StringComparer.Ordinal) && int.TryParse(heading.AsSpan(space + 1), NumberStyles.None, CultureInfo.InvariantCulture, out int _)
            ? this[heading[..space]] + heading[space..]
            : this[heading];
    }

    /// <summary>
    /// A message made by the server (rc.15, item 41), in this language. Most are fixed sentences
    /// in the word list; some carry a number or a name, such as "Your organisation allows 7 to 30
    /// days.". Such a message is recognised by its pattern in the word list ("Your organisation
    /// allows {min} to {max} days."), the pattern is put into this language, and the values go
    /// back in. A message that matches nothing is shown as it is and noted in <see cref="Unlisted"/>.
    /// </summary>
    /// <param name="message">The message in English.</param>
    /// <returns>The message to show.</returns>
    public string Say(string message)
    {
        ArgumentNullException.ThrowIfNull(message);
        if (Listed is not { } listed || listed.Contains(message))
        {
            return this[message];
        }
        foreach ((string template, System.Text.RegularExpressions.Regex pattern, string[] blanks) in Patterns.Value)
        {
            System.Text.RegularExpressions.Match m = pattern.Match(message);
            if (!m.Success)
            {
                continue;
            }
            string said = this[template];
            foreach (string blank in blanks)
            {
                said = said.Replace("{" + blank + "}", m.Groups[blank].Value, StringComparison.Ordinal);
            }
            return said;
        }
        return this[message];
    }

    private static readonly System.Text.RegularExpressions.Regex BlankRegex = new(@"\{([A-Za-z][A-Za-z0-9]*)\}", System.Text.RegularExpressions.RegexOptions.CultureInvariant);

    private static readonly Lazy<List<(string Template, System.Text.RegularExpressions.Regex Pattern, string[] Blanks)>> Patterns = new(() =>
    {
        var list = new List<(string, System.Text.RegularExpressions.Regex, string[])>();
        foreach (string word in Listed ?? new HashSet<string>())
        {
            System.Text.RegularExpressions.MatchCollection blanks = BlankRegex.Matches(word);
            if (blanks.Count == 0 || word.Length < 12)
            {
                continue;
            }
            string[] names = blanks.Select(b => b.Groups[1].Value).Distinct(StringComparer.Ordinal).ToArray();
            string regex = "^" + BlankRegex.Replace(System.Text.RegularExpressions.Regex.Escape(word).Replace("\\{", "{", StringComparison.Ordinal), b => "(?<" + b.Groups[1].Value + ">.+?)") + "$";
            list.Add((word, new System.Text.RegularExpressions.Regex(regex, System.Text.RegularExpressions.RegexOptions.CultureInvariant | System.Text.RegularExpressions.RegexOptions.Singleline, TimeSpan.FromMilliseconds(50)), names));
        }
        // The most specific pattern first: the one with the most fixed words.
        list.Sort((a, b) => BlankRegex.Replace(b.Item1, string.Empty).Length.CompareTo(BlankRegex.Replace(a.Item1, string.Empty).Length));
        return list;
    });

    /// <summary>A word in this language, or the English word when this language lacks it.</summary>
    /// <param name="english">The English word, exactly as in the word list.</param>
    /// <returns>The word to show.</returns>
    public string this[string english]
    {
        get
        {
            ArgumentNullException.ThrowIfNull(english);
            if (Listed is { } listed && english.Length > 0 && !listed.Contains(english) && Missed.Count < 1000)
            {
                Missed.TryAdd(english, true);
            }
            return this.words.TryGetValue(english, out string? word) && word.Length > 0 ? word : english;
        }
    }
}
