<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Anjal.Examples.OutboundEndToEnd</RootNamespace>
    <AssemblyName>Anjal.OutboundEndToEnd</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1303;CA1812;CA1515;CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Anjal.Mime\Anjal.Mime.csproj" />
    <ProjectReference Include="..\..\src\Anjal.Store\Anjal.Store.csproj" />
    <ProjectReference Include="..\..\src\Anjal.Smtp\Anjal.Smtp.csproj" />
    <ProjectReference Include="..\..\src\Anjal.Dns\Anjal.Dns.csproj" />
  </ItemGroup>

</Project>
