<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Anjal.Auth</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1303;CA1812;CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anjal.Dns\Anjal.Dns.csproj" />
    <ProjectReference Include="..\Anjal.Dkim\Anjal.Dkim.csproj" />
  </ItemGroup>

</Project>
