#!/usr/bin/env python3
"""Generate the webmail's tokens.css from the design system's tokens.json.

The design system "Anjal" is the single source of every colour, shadow,
spacing step, corner and type style. Copy its tokens.json to
tools/design/tokens.json, run this script, and commit both files.
Never edit tokens.css by hand.

The font stacks are the product's own: LiPi Sans, served by Anjal itself
(D-96). The design system's stacks also name Inter and Noto Sans so its
previews can show the letters; the product does not need those names.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "design" / "tokens.json"
OUT = ROOT / "src" / "Anjal.Webmail" / "wwwroot" / "tokens.css"

FONTS = {
    "display": '"LiPi Sans", system-ui, sans-serif',
    "sans": '"LiPi Sans", system-ui, -apple-system, sans-serif',
    "tamil": '"LiPi Sans", system-ui, sans-serif',
    "malayalam": '"LiPi Sans", system-ui, sans-serif',
    "devanagari": '"LiPi Sans", system-ui, sans-serif',
    "gujarati": '"LiPi Sans", system-ui, sans-serif',
}

# Rules the design system does not hold; kept exactly as before.
EXTRAS = """/* The favourite mark - the seal's own letter, set bare */
.anjal-fav { font-family: var(--font-tamil); font-size: 15px; line-height: 22px;
             font-weight: 600; color: var(--line-strong); user-select: none; }
.anjal-fav.is-set { color: var(--brand); }

/* Focus - never remove this, never make it dashed */
:focus-visible { outline: 2px solid var(--focus-ring); outline-offset: 2px; }
"""


# UX-09: every text and background pairing the screens use, with its WCAG
# minimum - 4.5:1 for text, 3:1 for edges, icons and the focus ring. A theme
# that falls below fails the generation, so no unreadable theme can ship.
CONTRAST_PAIRS = [
    ("ink", "surface-000", 4.5), ("ink", "surface-100", 4.5), ("ink", "surface-200", 4.5), ("ink", "surface-300", 4.5),
    ("ink-muted", "surface-000", 4.5), ("ink-muted", "surface-100", 4.5), ("ink-muted", "surface-200", 4.5),
    ("ink-subtle", "surface-100", 4.5), ("ink-subtle", "surface-200", 4.5),
    ("on-brand", "brand", 4.5), ("brand", "surface-100", 4.5), ("brand", "surface-200", 4.5),
    # the open item: dark ink on a visible tint (text), the theme colour as its icon (3:1)
    ("ink", "brand-soft", 4.5), ("brand", "brand-soft", 3.0),
    ("on-seal", "seal", 4.5), ("seal", "surface-200", 4.5),
    ("ink", "warning-soft", 4.5), ("ink", "danger-soft", 4.5), ("danger", "surface-200", 4.5), ("warning", "surface-200", 3.0),
    ("focus-ring", "surface-100", 3.0), ("focus-ring", "surface-200", 3.0), ("line-strong", "surface-200", 3.0),
]


def luminance(hex_colour):
    h = hex_colour.lstrip("#")
    channels = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def contrast_problems(themes, colours):
    values = {tok["name"]: tok["value"] for tok in colours}
    problems = []
    for theme in themes:
        tid = theme["id"]
        for fg, bg, minimum in CONTRAST_PAIRS:
            a, b = luminance(values[fg][tid]), luminance(values[bg][tid])
            ratio = (max(a, b) + 0.05) / (min(a, b) + 0.05)
            if ratio < minimum:
                problems.append(f"{tid}: {fg} on {bg} is {ratio:.2f}:1, needs {minimum}:1")
    return problems


def css_name(prop):
    out = []
    for ch in prop:
        out.append("-" + ch.lower() if ch.isupper() else ch)
    return "".join(out)


def main():
    tokens = json.loads(SRC.read_text(encoding="utf-8"))
    themes = tokens["color"]["themes"]
    colours = tokens["color"]["tokens"]
    shadows = tokens["shadow"]["tokens"]
    problems = contrast_problems(themes, colours)
    if problems:
        for p in problems:
            print("contrast: " + p, file=sys.stderr)
        return 1
    lines = [
        "/* Anjal design tokens - generated by tools/gen_tokens_css.py from tools/design/tokens.json. Do not edit by hand. */",
        f"/* {len(themes)} themes: the house colour Anjal and twenty named colours, each light and dark, plus each colour following the device (-auto). Set data-theme on <html>; {themes[0]['name']} is the default. */",
        "",
        '@import url("/fonts/lipi.css");   /* LiPi Sans - self-hosted, 10 scripts, no third-party request */',
        "",
    ]
    for i, theme in enumerate(themes):
        tid = theme["id"]
        selector = f':root,\n[data-theme="{tid}"]' if i == 0 else f'[data-theme="{tid}"]'
        lines.append(f"/* {theme['name']} */")
        lines.append(selector + " {")
        lines.append("  color-scheme: " + ("dark" if tid.endswith("-dark") else "light") + ";")
        for tok in colours:
            lines.append(f"  --{tok['name']}: {tok['value'][tid]};")
        for tok in shadows:
            lines.append(f"  --{tok['name']}: {tok['value'][tid]};")
        lines.append("}")
        lines.append("")
    # "Follow this device": each colour's -auto theme takes the light values,
    # and the dark ones when the device asks for dark. No script needed.
    by_id = {t["id"]: t for t in themes}
    colours_seen = []
    for theme in themes:
        colour = theme["id"].rsplit("-", 1)[0]
        if colour not in colours_seen:
            colours_seen.append(colour)
    for colour in colours_seen:
        light, dark = f"{colour}-light", f"{colour}-dark"
        if light not in by_id or dark not in by_id:
            continue
        for mode, wrap in (("light", None), ("dark", "@media (prefers-color-scheme: dark)")):
            tid = f"{colour}-{mode}"
            indent = "  " if wrap else ""
            if wrap:
                lines.append(wrap + " {")
            else:
                lines.append(f"/* {by_id[light]['name'].split(' (')[0]}, following the device */")
            lines.append(f'{indent}[data-theme="{colour}-auto"] {{')
            lines.append(f"{indent}  color-scheme: {mode};")
            for tok in colours:
                lines.append(f"{indent}  --{tok['name']}: {tok['value'][tid]};")
            for tok in shadows:
                lines.append(f"{indent}  --{tok['name']}: {tok['value'][tid]};")
            lines.append(f"{indent}}}")
            if wrap:
                lines.append("}")
        lines.append("")
    # Swatches for Settings > Appearance: each colour's own brand colour, so the
    # choice shown is exactly the theme it applies.
    lines.append("/* Theme swatches (Settings > Appearance) */")
    # The true named colour when the design system gives one (D-112); else the brand colour.
    swatch = next((t for t in colours if t["name"] == "swatch"), None) or next(t for t in colours if t["name"] == "brand")
    for colour in colours_seen:
        if f"{colour}-light" in by_id:
            lines.append(f".swatch-{colour} {{ background: {swatch['value'][colour + '-light']}; }}")
    lines.append("")
    lines.append("/* Scale - the same in every theme */")
    lines.append(":root {")
    for family in ("spacing", "radius", "opacity"):
        for tok in tokens[family]["tokens"]:
            lines.append(f"  --{tok['name']}: {tok['value']};")
    for key, stack in FONTS.items():
        lines.append(f"  --font-{key}: {stack};")
    lines.append(f"  --font-mono: {tokens['type']['families']['mono']};")
    lines.append("}")
    lines.append("")
    lines.append("/* Type scale - apply as classes, or copy the declarations */")
    for group in tokens["type"]["groups"]:
        lines.append(f"/* {group['name']} */")
        for style in group["styles"]:
            family = style.get("family", group["family"])
            if family == "tamil" and "-" in style["name"] and style["name"].split("-")[0] in FONTS:
                family = style["name"].split("-")[0]
            decl = [f"font-family: var(--font-{family})"]
            for prop in ("fontSize", "lineHeight", "fontWeight", "letterSpacing"):
                if prop in style:
                    decl.append(f"{css_name(prop)}: {style[prop]}")
            lines.append(f".{style['name']} {{ " + "; ".join(decl) + "; }")
        lines.append("")
    lines.append(EXTRAS)
    # CRLF, as .editorconfig asks for every file.
    text = "\n".join(lines).replace("\r\n", "\n")
    OUT.write_bytes(text.replace("\n", "\r\n").encode("utf-8"))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(themes)} themes, {len(colours) + len(shadows)} values each; contrast checked: {len(themes) * len(CONTRAST_PAIRS)} pairings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
