<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Anjal.Examples.MimeBuild</RootNamespace>
    <AssemblyName>Anjal.Mime.Build</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1303;CA1812;CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Anjal.Mime\Anjal.Mime.csproj" />
  </ItemGroup>

</Project>
